# Generated by Django 2.1.3 on 2018-12-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('term', models.IntegerField(null=True)),
                ('legislative_year', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('filename', models.CharField(max_length=5, null=True)),
                ('document_type', models.CharField(choices=[('term', 'Term'), ('catalog', 'Catalog'), ('agenda', 'Agenda')], max_length=16)),
                ('session', models.CharField(max_length=3, null=True)),
                ('parliament_type', models.CharField(choices=[('tbmm', 'TBMM'), ('csenate', 'csenate'), ('mgk', 'MGK'), ('csession', 'csession'), ('tbt', 'TBT'), ('ca', 'CA')], max_length=16)),
            ],
        ),
    ]
