# Generated by Django 2.1.4 on 2019-01-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parliamenttext',
            name='document_type',
            field=models.CharField(choices=[('session', 'session'), ('catalog', 'catalog'), ('agenda', 'agenda')], max_length=16),
        ),
        migrations.AlterField(
            model_name='parliamenttext',
            name='parliament_type',
            field=models.CharField(choices=[('csenate', 'csenate'), ('csession', 'csession'), ('ca', 'ca'), ('mgk', 'mgk'), ('na', 'na'), ('tbt', 'tbt'), ('tbmm', 'tbmm')], max_length=16),
        ),
    ]
