# Generated by Django 2.1.4 on 2019-01-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20190103_1242'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parliamenttext',
            index=models.Index(fields=['document_type'], name='corpus_parl_documen_895131_idx'),
        ),
        migrations.AddIndex(
            model_name='parliamenttext',
            index=models.Index(fields=['parliament_type'], name='corpus_parl_parliam_128b99_idx'),
        ),
    ]
